{% set version = "3.1.3" %}

package:
  name: wgrib2
  version: {{ version }}

source:
  fn: wgrib2_nolib.tgz
  url: https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2_nolib.tgz.v{{ version }}
  sha256: 79ee6e3aa15f90cc1a03ece9ba8ade7ded11017ede09ff658ea7b3b3e077801c
  patches:
    - no_proj.patch
    - jasper4.patch

build:
  number: 7
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - g2clib
    - mysql-devel
    - libaec
    - libnetcdf
    - libpng
    - zlib
    - jasper
  run:
    - g2clib
    - mysql-libs
    - libaec
    - libnetcdf
    - libpng
    - zlib
    - jasper

test:
  files:
    - file.grib2
  commands:
    # - wgrib2 -config # works but the return code !=0
    - wgrib2 file.grib2 -netcdf out.nc

about:
  home: http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2
  license: GPL-2.0-or-later
  license_file: wgrib2/LICENSE-wgrib2
  summary: Utility to read and write grib2 files

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - akrherz
