schema_version: 1

context:
  version: "3.8.0"

package:
  name: wgrib2
  version: ${{ version }}

source:
  url: https://github.com/NOAA-EMC/wgrib2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 39faebada36da5457c75f0980bb68fa299b221b3e6b335bb7d29006a35830c54
  file_name: wgrib2_nolib.tgz
  patches:
    # NOAA-EMC/wgrib2/510
    - gh510_posix.patch

build:
  number: 7
  skip: win
  prefix_detection:
    ignore_binary_files: false

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
  host:
    - g2clib
    - mysql-devel
    - libaec
    - libnetcdf
    - libpng
    - nceplibs-ip
    - zlib
    - jasper
  run:
    - g2clib
    - mysql-libs
    - libaec
    - libnetcdf
    - nceplibs-ip
    - libpng
    - zlib
    - jasper

tests:
  - files:
      recipe:
        - file.grib2
    script:
      - wgrib2 file.grib2 -netcdf out.nc

about:
  license: GPL-2.0-or-later
  license_file: wgrib2/LICENSE-wgrib2
  summary: Utility to read and write grib2 files
  homepage: http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - akrherz
