travis:
  secure:
    BINSTAR_TOKEN: aJTX431bcXeqiN7+YinsEo0AzBsnVPUEpinejU/bnt30OmvmmNkk61j9nfw6T6unu1QXaLgCglfuucc524cDAkRxL5KOU2s7P4SngeiN/Gm7uEkGLtSySoorPlEumIRaufxil5DzTZb4KyDHjB/W0i1VjfPIcFL+VdQxzCyvJKZaBByQLBVl1cNrXbr8/s4BYBe8Jkc9a37ZISowoLO21Jjw+YDzi6qhEt0uZCaiV0yyvsgCypzsRcpVhO0MvEyXClpb8mb0f495PyL6Y7RbwlbZFnqIffPZ5SbRSCkcNGdjDFs+W8YKP4Wkg6fJm6lrx23b0lqM1Y8x1UA+oEyJ8yj/m0WTm1dQHIx+AJXOhQcqE82v5IMM+MxGU9hp8m7e4rG7DlA6ew04Zzkk2DmPK2obQx6fzZfkHiiHmhyIedynsKXLAnTVE+HPlD/VmtRJFwmdB0Nqb79m9sP5ercwj/irWQ/bPaZT9zYSiR/IeCrPUT7e/Nm1Mk3/WjrZ4cDfM1dV4JCj10H7/JNopttrNEoeSG5pCCl5Qk78uNWLdlc0GWa9kkjDPVXQcWNcFjelDEHa0A6Ml4CS5yACpFYKzqp6hEVxRaXP3GebO98YQRmKKwJtnidjB79+1bY3Q90BF9KVZk34iFJO9MKZrCp2g/1zgroRPpfODEgJoiDUkO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
